### ISSUE TITLE
Unrealistic physics

### ISSUE THREAD

**Issue by Malhonnete** [GDsouza/CitationX-PAFTeam#1]
I'm not professional but I'm sure physics are very unrealistic.

**Comment by GDsouza** [comment]
Hi @Malhonnete, this is just a mirror of the project that I maintain for convenience. 
Issues should go to the [repository](https://sourceforge.net/p/pafteam/addons/ci/master/tree/Aircraft/CitationX/) or [forum](https://equipe-flightgear.forumactif.com/)
